(function (root, factory) {
  const activities = factory();
  if (typeof module === "object" && module.exports) module.exports = activities;
  root.ACTIVITIES = activities;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  const single = (id, subject, category, visual, question, options, correct, explanation) => ({
    id, subject, category, visual, type: "single", activity: "Elegí la respuesta correcta",
    question, options, correct, explanation
  });
  const multi = (id, subject, category, visual, question, options, correct, explanation) => ({
    id, subject, category, visual, type: "multi", choose: correct.length,
    activity: `Seleccioná ${correct.length} respuestas`, question, options, correct, explanation
  });

  return [
    single("science-biodiversity", "Ciencias", "Biodiversidad", "🌿🦥🦋",
      "¿Cómo se llama el conjunto de diversas especies de flora y fauna que habitan en un lugar determinado?",
      ["Biodiversidad", "Población", "Nicho", "Hábitat"], "Biodiversidad",
      "La biodiversidad es la variedad de seres vivos que habitan en un lugar."),
    single("science-costa-rica-location", "Ciencias", "Biodiversidad", "🇨🇷🌎",
      "¿Qué característica de Costa Rica favorece que sea uno de los países más biodiversos del mundo?",
      ["Su ubicación en la zona intertropical", "Su tamaño territorial", "La ausencia de montañas", "Un único tipo de clima"],
      "Su ubicación en la zona intertropical",
      "La ubicación de Costa Rica en la zona intertropical favorece climas y ambientes donde viven muchas especies."),
    single("science-fish-breathing", "Ciencias", "Adaptaciones", "🐟💧",
      "¿Qué adaptación utiliza el pez para respirar?", ["Branquias", "Pulmones", "Piel", "Tráqueas"], "Branquias",
      "Los peces toman el oxígeno disuelto en el agua mediante las branquias."),
    single("science-dolphin-breathing", "Ciencias", "Adaptaciones", "🐬🌊",
      "¿Qué órgano utiliza el delfín para respirar?", ["Pulmones", "Branquias", "Piel", "Tráqueas"], "Pulmones",
      "El delfín es un mamífero y respira aire mediante pulmones, aunque viva en el agua."),
    single("science-frog-breathing", "Ciencias", "Adaptaciones", "🐸",
      "En la actividad ilustrada, ¿qué adaptación respiratoria se asocia con la rana?", ["Piel", "Branquias", "Tráqueas", "Aletas"], "Piel",
      "Las ranas adultas pueden intercambiar gases a través de su piel húmeda."),
    single("science-butterfly-breathing", "Ciencias", "Adaptaciones", "🦋",
      "¿Qué adaptación utiliza la mariposa para respirar?", ["Tráqueas", "Pulmones", "Branquias", "Piel"], "Tráqueas",
      "Los insectos, como la mariposa, respiran mediante un sistema de tráqueas."),
    single("science-dog-breathing", "Ciencias", "Adaptaciones", "🐕",
      "¿Qué órgano utiliza el perro para respirar?", ["Pulmones", "Branquias", "Tráqueas", "Piel"], "Pulmones",
      "El perro es un mamífero terrestre y respira mediante pulmones."),
    single("science-mammals", "Ciencias", "Reproducción", "🐄🥛",
      "Son seres vivos que llevan a sus crías en el vientre durante el desarrollo y, al nacer, las alimentan con leche materna. ¿Qué grupo es?",
      ["Mamíferos", "Reptiles", "Peces", "Insectos"], "Mamíferos",
      "Los mamíferos se desarrollan en el vientre en la mayoría de los casos y sus crías se alimentan con leche materna."),
    single("science-relief", "Ciencias", "Biodiversidad", "⛰️🌋🌧️",
      "Costa Rica posee cordilleras, volcanes y llanuras. ¿Por qué ese relieve favorece una gran biodiversidad?",
      ["Produce distintas alturas, condiciones, ecosistemas y microclimas", "Hace que todo el país tenga el mismo clima", "Elimina los bosques", "Impide la vida de muchas especies"],
      "Produce distintas alturas, condiciones, ecosistemas y microclimas",
      "Las distintas alturas y formas del relieve crean condiciones variadas, ecosistemas y microclimas."),
    single("science-fire-threat", "Ciencias", "Amenazas", "🔥🌳",
      "Don Manuel quema vegetación seca antes de sembrar y pone en riesgo los bosques vecinos. ¿Qué amenaza representa esta práctica?",
      ["Incendios forestales", "Reforestación", "Ecoturismo", "Protección de especies"], "Incendios forestales",
      "Quemar vegetación puede hacer que el fuego se salga de control y provoque incendios forestales."),
    single("science-individual", "Ciencias", "Ecosistema", "🦥",
      "¿Cómo se llama un solo ser vivo u organismo único?", ["Individuo", "Población", "Hábitat", "Nicho"], "Individuo",
      "Un individuo es un único organismo, por ejemplo un solo perezoso."),
    single("science-population", "Ciencias", "Ecosistema", "🐒🐒🐒",
      "¿Cómo se llama un grupo de individuos de la misma especie que vive en un área?",
      ["Población", "Individuo", "Hábitat", "Nicho"], "Población",
      "Una población reúne individuos de la misma especie que viven en un área determinada."),
    single("science-habitat", "Ciencias", "Ecosistema", "🏞️",
      "¿Cómo se llama el lugar físico donde vive y se desarrolla un organismo?",
      ["Hábitat", "Nicho", "Población", "Individuo"], "Hábitat",
      "El hábitat es el lugar físico que brinda las condiciones necesarias para vivir."),
    single("science-niche", "Ciencias", "Ecosistema", "🐝🌼",
      "¿Cómo se llama la función o el papel que cumple un ser vivo en su hábitat?",
      ["Nicho", "Hábitat", "Población", "Individuo"], "Nicho",
      "El nicho describe el papel del organismo: qué come, cómo vive y cómo se relaciona."),
    multi("science-natural-aspects", "Ciencias", "Biodiversidad", "🇨🇷🌋🌦️",
      "Seleccioná TRES aspectos naturales que determinan la gran biodiversidad de Costa Rica.",
      ["Ubicación intertropical", "Variedad del relieve", "Diversidad de climas", "Cantidad de edificios", "Número de carreteras"],
      ["Ubicación intertropical", "Variedad del relieve", "Diversidad de climas"],
      "La ubicación intertropical, el relieve variado y los diferentes climas crean muchos ambientes naturales."),
    multi("science-natural-energy", "Ciencias", "Energía", "☀️💨",
      "Seleccioná DOS ejemplos de energía que se manifiestan en el entorno natural.",
      ["Energía solar", "Energía eólica", "Gasolina", "Batería desechable"],
      ["Energía solar", "Energía eólica"],
      "La energía solar proviene del Sol y la eólica se obtiene del viento."),
    multi("science-mechanical-states", "Ciencias", "Energía", "🎢⚡",
      "¿Cuáles son los DOS estados en que se transforma la energía mecánica?",
      ["Energía potencial", "Energía cinética", "Energía química", "Energía luminosa"],
      ["Energía potencial", "Energía cinética"],
      "La energía mecánica puede presentarse como potencial, por la posición, y cinética, por el movimiento."),
    multi("science-human-threats", "Ciencias", "Amenazas", "🪓🦜",
      "Seleccioná DOS amenazas producidas por el ser humano contra la biodiversidad.",
      ["Deforestación", "Tráfico ilegal de especies", "Reforestación", "Protección de parques"],
      ["Deforestación", "Tráfico ilegal de especies"],
      "La pérdida de bosques y la captura o venta ilegal de especies dañan la biodiversidad."),
    multi("science-benefits", "Ciencias", "Biodiversidad", "🌿💊",
      "Seleccioná DOS beneficios que obtiene Costa Rica por su biodiversidad.",
      ["Ecoturismo", "Obtención de medicinas", "Aumento de incendios", "Pérdida de hábitats"],
      ["Ecoturismo", "Obtención de medicinas"],
      "La biodiversidad atrae turismo de naturaleza y aporta organismos útiles para producir medicinas."),
    single("science-ball-energy", "Ciencias", "Energía", "⚾⬇️",
      "Una pelota cae desde una mesa. ¿Cómo se transforma su energía?",
      ["De energía potencial a energía cinética", "De energía cinética a potencial", "De energía solar a química", "No ocurre transformación"],
      "De energía potencial a energía cinética",
      "En la mesa posee energía potencial por su altura; al caer y moverse, esa energía se transforma en cinética."),
    single("science-cart-energy", "Ciencias", "Energía", "🛒⛰️",
      "Un carrito baja a gran velocidad desde el punto más alto de una montaña rusa. ¿Qué transformación ocurre?",
      ["De energía potencial a energía cinética", "De energía cinética a potencial", "De energía eólica a solar", "De energía térmica a química"],
      "De energía potencial a energía cinética",
      "En lo alto tiene mayor energía potencial y al bajar se convierte en energía cinética de movimiento."),
    single("science-wind-energy", "Ciencias", "Energía", "💨",
      "¿Qué clase de energía se manifiesta a través de las corrientes de aire o viento?",
      ["Energía eólica", "Energía potencial", "Energía química", "Energía sonora"], "Energía eólica",
      "La energía eólica es la energía obtenida del movimiento del viento."),
    single("science-apple-energy", "Ciencias", "Energía", "🍎🌳",
      "La energía almacenada en una manzana que todavía cuelga de un árbol, por su posición, se denomina…",
      ["Energía potencial", "Energía cinética", "Energía eólica", "Energía sonora"], "Energía potencial",
      "La manzana tiene energía potencial porque está almacenada debido a su posición y altura."),
    single("science-illegal-trade", "Ciencias", "Amenazas", "🐒🚫",
      "Un comerciante captura monos tití y perezosos para venderlos como mascotas fuera del país. ¿Qué amenaza representa?",
      ["Tráfico ilegal de especies", "Reforestación", "Ecoturismo", "Agricultura sostenible"], "Tráfico ilegal de especies",
      "Capturar y vender fauna silvestre sin autorización es tráfico ilegal de especies."),

    single("spanish-environment", "Español", "Elementos del texto", "🌙📖",
      "Es el lugar y el momento en que ocurren los hechos del texto. ¿Cómo se llama?",
      ["Ambiente", "Trama textual", "Conflicto", "Personaje"], "Ambiente",
      "El ambiente indica dónde y cuándo ocurren los hechos de una historia."),
    single("spanish-plot", "Español", "Elementos del texto", "🧩📚",
      "Es el conjunto de hechos que suceden a lo largo del texto. ¿Cómo se llama?",
      ["Trama textual", "Ambiente", "Moraleja", "Diccionario"], "Trama textual",
      "La trama textual es la secuencia de acontecimientos que forman la historia."),
    single("spanish-cause-effect", "Español", "Elementos del texto", "➡️💥",
      "¿Qué relación explica cómo una acción provoca una consecuencia dentro del texto?",
      ["Relación causa y efecto", "Ambiente temporal", "Descripción física", "Trama final"], "Relación causa y efecto",
      "La causa es lo que ocurre primero y el efecto es la consecuencia que produce."),
    single("spanish-conflict", "Español", "Elementos del texto", "⚠️👧",
      "Es el problema o la situación principal que enfrentan los personajes. ¿Cómo se llama?",
      ["Conflicto o situación", "Ambiente", "Inicio", "Definición"], "Conflicto o situación",
      "El conflicto es la dificultad principal que los personajes deben enfrentar."),
    single("spanish-characteristics", "Español", "Personajes", "🙂💭",
      "Son los rasgos físicos, emocionales y de personalidad que describen a los personajes. ¿Qué son?",
      ["Características de los personajes", "Ambiente", "Trama textual", "Causa y efecto"], "Características de los personajes",
      "Las características permiten saber cómo es un personaje por fuera, cómo se siente y cómo actúa."),
    single("spanish-storm", "Español", "Vocabulario", "⛈️",
      "El meteorólogo anunció una fuerte TORMENTA. ¿Cuál definición corresponde?",
      ["Alteración atmosférica acompañada de lluvia, viento o rayos", "Día despejado", "Movimiento suave de hojas", "Lugar para observar estrellas"],
      "Alteración atmosférica acompañada de lluvia, viento o rayos",
      "Una tormenta es una alteración atmosférica que puede incluir lluvia fuerte, viento, truenos o rayos."),
    single("spanish-wilted", "Español", "Vocabulario", "🥀",
      "La pequeña planta estaba MARCHITA porque sus hojas estaban secas y caídas. ¿Qué significa marchita?",
      ["Seca y sin vitalidad", "Recién sembrada", "Llena de flores", "Muy alta y fuerte"], "Seca y sin vitalidad",
      "Marchita significa que una planta ha perdido frescura o vitalidad y se ve seca o caída."),
    single("spanish-landscape", "Español", "Diccionario", "🏞️📖",
      "La familia contempló un paisaje de montañas, árboles y un río. ¿Cuál definición de PAISAJE corresponde?",
      ["Extensión de terreno que puede observarse desde un lugar", "Objeto para medir", "Sonido de instrumentos", "Persona que viaja por mar"],
      "Extensión de terreno que puede observarse desde un lugar",
      "En la oración, paisaje es la extensión de terreno que las personas pueden observar."),
    single("spanish-navigator", "Español", "Diccionario", "🔤📘",
      "Alonso necesita buscar NAVEGANTE en el diccionario. ¿En cuál sección debe iniciar?",
      ["Letra N", "Letra A", "Letra G", "Letra V"], "Letra N",
      "Las palabras se buscan por su primera letra y navegante comienza con N."),
    single("spanish-context", "Español", "Diccionario", "🔎📖",
      "Sofía encontró tres significados para una palabra. ¿Qué debe hacer para elegir el correcto?",
      ["Comparar las definiciones con el contexto de la oración", "Elegir la primera", "Escoger la más corta", "Usar cualquiera"],
      "Comparar las definiciones con el contexto de la oración",
      "El contexto permite decidir cuál significado corresponde a la oración."),
    single("spanish-microscope", "Español", "Diccionario", "🔬",
      "La científica observó una célula utilizando un MICROSCOPIO. ¿Cuál definición corresponde?",
      ["Instrumento que permite observar objetos muy pequeños", "Objeto para orientarse", "Máquina para medir el viento", "Recipiente para sembrar"],
      "Instrumento que permite observar objetos muy pequeños",
      "Un microscopio permite ampliar y observar objetos demasiado pequeños para verlos a simple vista."),
    single("spanish-feather", "Español", "Diccionario", "🪶✍️",
      "La palabra PLUMA puede ser una estructura de las aves o un instrumento para escribir. En «firmó con una pluma», ¿cuál corresponde?",
      ["La segunda definición: instrumento para escribir", "La primera definición: estructura de las aves", "Las dos al mismo tiempo", "Ninguna"],
      "La segunda definición: instrumento para escribir",
      "El contexto «firmó» indica que pluma se usa como instrumento para escribir."),
    single("spanish-bird-ending", "Español", "Comprensión", "🐦🌿",
      "Julián alimentaba aves. Encontró un pajarito herido y llamó a rescate. Días después se recuperó. ¿Qué ocurre al final?",
      ["El ave se recuperó y fue liberada", "Julián encontró al ave", "Julián llevó alimento", "El ave siguió herida"],
      "El ave se recuperó y fue liberada",
      "El acontecimiento final es la recuperación y liberación del ave."),
    single("spanish-fable", "Español", "Fábulas", "🐦🌧️",
      "Un cuervo acapara semillas, la lluvia se las lleva y otros pájaros comparten con él. ¿Por qué es una fábula?",
      ["Presenta animales que actúan como personas y deja una moraleja", "Solo describe la lluvia", "Da instrucciones", "Cuenta una noticia real"],
      "Presenta animales que actúan como personas y deja una moraleja",
      "Las fábulas suelen presentar animales con conductas humanas y transmiten una enseñanza."),
    single("spanish-plant-conflict", "Español", "Comprensión", "🪴💔",
      "Natalia lleva una planta a la escuela y descubre que una rama se quebró. ¿Cuál es el conflicto?",
      ["La rama de la planta se quebró", "Natalia llegó a la escuela", "La escuela hizo una feria", "Natalia presentó el proyecto"],
      "La rama de la planta se quebró",
      "El conflicto es el problema que dificulta el objetivo del personaje: la rama quebrada."),
    single("spanish-beaver-lesson", "Español", "Fábulas", "🐿️🦫",
      "Una ardilla se burló de un castor que tardó en construir. En una tormenta, el refugio del castor lo mantuvo seguro. ¿Cuál es la enseñanza?",
      ["El trabajo constante produce buenos resultados", "Construir rápido siempre es mejor", "Burlarse ayuda a los demás", "Las tormentas no son peligrosas"],
      "El trabajo constante produce buenos resultados",
      "La constancia del castor permitió construir un refugio seguro."),
    single("spanish-touch-sky", "Español", "Expresiones", "☁️🙌",
      "Daniel sintió que TOCABA EL CIELO CON LAS MANOS al recibir la noticia. ¿Qué significa?",
      ["Que estaba muy feliz por la noticia", "Que subió a una montaña", "Que tocó una nube", "Que midió el cielo"],
      "Que estaba muy feliz por la noticia",
      "Tocar el cielo con las manos es una expresión figurada que significa sentirse extremadamente feliz."),
    single("spanish-development", "Español", "Comprensión", "🌱💧🌼",
      "Óscar sembró semillas, después las regó y cuidó, y finalmente aparecieron flores. ¿Qué pertenece al desarrollo?",
      ["Óscar regó y cuidó las semillas", "Óscar sembró las semillas", "Aparecieron flores", "Óscar compró una maceta"],
      "Óscar regó y cuidó las semillas",
      "El desarrollo contiene las acciones entre el inicio y el final."),
    single("spanish-generous", "Español", "Vocabulario", "🤝",
      "La señora fue GENEROSA y compartió sus alimentos. ¿Qué significa generosa?",
      ["Que comparte lo que tiene con otras personas", "Que posee bastante espacio", "Que no es verdadera", "Que puede provocar una caída"],
      "Que comparte lo que tiene con otras personas",
      "Una persona generosa comparte o da a otras personas de manera desinteresada."),
    single("spanish-spacious", "Español", "Vocabulario", "🏠↔️",
      "La habitación era AMPLIA y cabían muchas personas. ¿Qué significa amplia?",
      ["Que posee bastante espacio", "Que puede provocar una caída", "Que no es verdadera", "Que actúa con cuidado"],
      "Que posee bastante espacio",
      "Amplia significa que tiene bastante espacio o que es espaciosa."),
    single("spanish-false", "Español", "Vocabulario", "📰❌",
      "La noticia era FALSA y no correspondía con la realidad. ¿Qué significa falsa?",
      ["Que no es verdadera", "Que posee bastante espacio", "Que comparte lo que tiene", "Que actúa con cuidado"],
      "Que no es verdadera",
      "Falsa significa que algo no es verdadero o no corresponde con la realidad."),
    single("spanish-prudent", "Español", "Vocabulario", "🪜👷",
      "El trabajador fue PRUDENTE y revisó la escalera antes de subir. ¿Qué significa prudente?",
      ["Que actúa con cuidado para evitar peligros", "Que no es verdadera", "Que comparte lo que tiene", "Que posee espacio"],
      "Que actúa con cuidado para evitar peligros",
      "Ser prudente significa actuar con cuidado para prevenir riesgos."),
    single("spanish-slippery", "Español", "Vocabulario", "🌧️🛣️",
      "El camino estaba RESBALADIZO después de la lluvia. ¿Qué significa resbaladizo?",
      ["Que puede provocar una caída", "Que posee bastante espacio", "Que no es verdadero", "Que comparte lo que tiene"],
      "Que puede provocar una caída",
      "Una superficie resbaladiza facilita que una persona se deslice y caiga."),
    single("spanish-night", "Español", "Ambiente", "🌙🔥🦗",
      "La luna iluminaba el camino y los campistas contaban historias junto a una fogata. ¿Cuál es el ambiente temporal?",
      ["La noche", "La mañana", "El mediodía", "La tarde"], "La noche",
      "La luna y el canto de los grillos indican que los hechos ocurren de noche."),
    single("spanish-custom", "Español", "Comprensión", "🫔👨‍👩‍👧‍👦",
      "Todos los años, en diciembre, la familia de Carmen prepara tamales. ¿Qué elemento se presenta?",
      ["Una costumbre familiar", "Un conflicto", "Una noticia", "Una tormenta"], "Una costumbre familiar",
      "La actividad se repite cada año dentro de la familia, por eso es una costumbre familiar."),
    multi("spanish-fables", "Español", "Fábulas", "🦁🐭🐢🐇",
      "Elegí DOS fábulas conocidas.",
      ["La liebre y la tortuga", "El león y el ratón", "Caperucita Roja", "Los tres cerditos"],
      ["La liebre y la tortuga", "El león y el ratón"],
      "La liebre y la tortuga y El león y el ratón son fábulas que presentan enseñanzas."),
    multi("spanish-tales", "Español", "Cuentos", "🐺🏠👧",
      "Elegí DOS cuentos conocidos.",
      ["Los tres cerditos", "Caperucita Roja", "La liebre y la tortuga", "El león y el ratón"],
      ["Los tres cerditos", "Caperucita Roja"],
      "Los tres cerditos y Caperucita Roja son cuentos tradicionales."),

    single("social-sports", "Estudios Sociales", "Actividades del cantón", "⚽🏃",
      "¿Qué tipo de actividades permiten a los residentes del cantón participar en ejercicio físico?",
      ["Deportivas", "Culturales", "Religiosas", "Ambientales"], "Deportivas",
      "Las actividades deportivas incluyen ejercicio físico, juegos y deportes."),
    single("social-recreation", "Estudios Sociales", "Actividades del cantón", "🛝👨‍👩‍👧",
      "¿Qué actividades ofrecen espacios para que las familias se diviertan sanamente en compañía?",
      ["Recreativas", "Religiosas", "Ambientales", "Culturales"], "Recreativas",
      "Las actividades recreativas brindan diversión, descanso y convivencia sana."),
    single("social-environmental", "Estudios Sociales", "Actividades del cantón", "🌳♻️",
      "¿Qué actividades permiten que los residentes contribuyan a proteger el medio ambiente?",
      ["Ambientales", "Deportivas", "Religiosas", "Recreativas"], "Ambientales",
      "Las actividades ambientales buscan cuidar y proteger la naturaleza."),
    single("social-cultural", "Estudios Sociales", "Actividades del cantón", "🎭🎨",
      "¿Qué actividades permiten que las personas expresen sus tradiciones y costumbres?",
      ["Culturales", "Deportivas", "Ambientales", "Recreativas"], "Culturales",
      "Las actividades culturales expresan las tradiciones, costumbres y manifestaciones artísticas."),
    single("social-religious", "Estudios Sociales", "Actividades del cantón", "🕊️⛪",
      "¿Qué actividades proporcionan espacios para que las personas expresen sus creencias y compartan valores?",
      ["Religiosas", "Culturales", "Deportivas", "Ambientales"], "Religiosas",
      "Las actividades religiosas permiten expresar creencias y compartir valores."),
    single("social-wind-rose", "Estudios Sociales", "Orientación", "🧭✳️",
      "¿Cómo se llama el símbolo que muestra los puntos cardinales y las direcciones?",
      ["Rosa de los vientos", "Brújula", "Mapa político", "Semáforo"], "Rosa de los vientos",
      "La rosa de los vientos representa los puntos cardinales y otras direcciones."),
    single("social-compass", "Estudios Sociales", "Orientación", "🧭",
      "¿Cómo se llama el instrumento con una aguja que permite orientarse?",
      ["Brújula", "Rosa de los vientos", "Termómetro", "Reloj"], "Brújula",
      "La brújula utiliza una aguja que señala el norte y ayuda a orientarse."),
    multi("social-cardinal-points", "Estudios Sociales", "Puntos cardinales", "🧭",
      "Seleccioná los CUATRO puntos cardinales.",
      ["Norte", "Este", "Oeste", "Sur", "Arriba", "Centro"],
      ["Norte", "Este", "Oeste", "Sur"],
      "Los cuatro puntos cardinales son norte, este, oeste y sur."),
    single("social-north", "Estudios Sociales", "Puntos cardinales", "⬆️🧭",
      "En una rosa de los vientos, ¿qué punto cardinal aparece normalmente arriba?",
      ["Norte", "Sur", "Este", "Oeste"], "Norte",
      "En la orientación convencional, el norte se representa en la parte superior."),
    single("social-east", "Estudios Sociales", "Puntos cardinales", "➡️🌅",
      "En una rosa de los vientos, ¿qué punto cardinal aparece a la derecha?",
      ["Este", "Oeste", "Norte", "Sur"], "Este",
      "El este se representa a la derecha y es la dirección aproximada por donde sale el Sol."),
    single("social-west", "Estudios Sociales", "Puntos cardinales", "⬅️🌇",
      "En una rosa de los vientos, ¿qué punto cardinal aparece a la izquierda?",
      ["Oeste", "Este", "Norte", "Sur"], "Oeste",
      "El oeste se representa a la izquierda y es la dirección aproximada por donde se oculta el Sol."),
    single("social-south", "Estudios Sociales", "Puntos cardinales", "⬇️🧭",
      "En una rosa de los vientos, ¿qué punto cardinal aparece abajo?",
      ["Sur", "Norte", "Este", "Oeste"], "Sur",
      "El sur se representa en la parte inferior y está en dirección opuesta al norte.")
  ];
});
