/* Banco de retos — basado en el temario del examen:
   1-2: Community helpers + places · 3: Goods & services
   4-5: -op / -og word families · 6: comprensión · 7: Where can I...? · 8: la fecha */

const QUESTION_BANK = [
  /* ============ COMMUNITY HELPERS ============ */
  { topic: "helpers", visual: "👩⚕️", speak: "She takes care of my health. Who is she?",
    q: "She takes care of my health. Who is she?",
    t: "Ella cuida mi salud. ¿Quién es?",
    options: ["Nurse 👩⚕️", "Farmer 👨🌾", "Mechanic 🔧"], correct: 0,
    explain: "«Nurse» significa enfermera. La enfermera cuida tu salud: she takes care of my health." },
  { topic: "helpers", visual: "👨🌾", speak: "He grows fruits and vegetables. Who is he?",
    q: "He grows fruits and vegetables. Who is he?",
    t: "Él cultiva frutas y verduras. ¿Quién es?",
    options: ["Doctor 🩺", "Farmer 👨🌾", "Teacher 🍎"], correct: 1,
    explain: "«Farmer» significa agricultor. El farmer cultiva frutas y verduras en el campo." },
  { topic: "helpers", visual: "🔧", speak: "He fixes cars. Who is he?",
    q: "He fixes cars. Who is he?",
    t: "Él arregla carros. ¿Quién es?",
    options: ["Mechanic 🔧", "Nurse 👩⚕️", "Baker 🥖"], correct: 0,
    explain: "«Mechanic» significa mecánico. El mecánico arregla los carros: he fixes cars." },
  { topic: "helpers", visual: "🩺", speak: "The doctor works at the...",
    q: "The doctor works at the...",
    t: "El doctor trabaja en el...",
    options: ["hospital 🏥", "bakery 🥖", "church ⛪"], correct: 0,
    explain: "El doctor trabaja en el hospital. «He works at the hospital»." },
  { topic: "helpers", visual: "🍎", speak: "She works at a school. Who is she?",
    q: "She works at a school. Who is she?",
    t: "Ella trabaja en una escuela. ¿Quién es?",
    options: ["Mechanic 🔧", "Farmer 👨🌾", "Teacher 🍎"], correct: 2,
    explain: "«Teacher» significa maestra. La maestra trabaja en la escuela: she works at a school." },
  { topic: "helpers", visual: "🚒", speak: "He puts out fires. Who is he?",
    q: "He puts out fires. Who is he?",
    t: "Él apaga incendios. ¿Quién es?",
    options: ["Fire fighter 🚒", "Doctor 🩺", "Farmer 👨🌾"], correct: 0,
    explain: "«Fire fighter» significa bombero. El bombero apaga los incendios." },
  { topic: "helpers", visual: "🦷", speak: "She takes care of my teeth. Who is she?",
    q: "She takes care of my teeth. Who is she?",
    t: "Ella cuida mis dientes. ¿Quién es?",
    options: ["Nurse 👩⚕️", "Dentist 🦷", "Teacher 🍎"], correct: 1,
    explain: "«Dentist» significa dentista. El dentista cuida tus dientes: teeth significa dientes." },

  /* ============ PLACES IN THE COMMUNITY ============ */
  { topic: "places", visual: "🥖", speak: "Where can I buy bread?",
    q: "Where can I buy bread? 🍞",
    t: "¿Dónde puedo comprar pan?",
    options: ["At the bakery 🥖", "At the hospital 🏥", "At the church ⛪"], correct: 0,
    explain: "«Bakery» significa panadería. El pan (bread) se compra en la bakery." },
  { topic: "places", visual: "🏥", speak: "I am sick. Where do I go?",
    q: "I am sick. Where do I go? 🤒",
    t: "Estoy enfermo. ¿A dónde voy?",
    options: ["To the bakery 🥖", "To the hospital 🏥", "To the shoe store 👟"], correct: 1,
    explain: "«Hospital» es hospital. Si estás enfermo (sick), vas al hospital." },
  { topic: "places", visual: "💊", speak: "Where can I buy medicine?",
    q: "Where can I buy medicine? 💊",
    t: "¿Dónde puedo comprar medicina?",
    options: ["At the church ⛪", "At the bakery 🥖", "At the drugstore 💊"], correct: 2,
    explain: "«Drugstore» significa farmacia. La medicina se compra en la drugstore." },
  { topic: "places", visual: "⛪", speak: "Church",
    q: "¿Qué significa «church»?",
    t: "Escuchá la palabra y elegí.",
    options: ["Iglesia ⛪", "Escuela 🏫", "Panadería 🥖"], correct: 0,
    explain: "«Church» significa iglesia. Se pronuncia «cherch»." },
  { topic: "places", visual: "🏫", speak: "The children study at the school.",
    q: "The children study at the...",
    t: "Los niños estudian en la...",
    options: ["drugstore 💊", "school 🏫", "bakery 🥖"], correct: 1,
    explain: "«School» significa escuela. Los niños estudian en la school." },
  { topic: "places", visual: "🗺️", speak: "Bakery, hospital, church, drugstore.",
    q: "¿Cuál de estos es un lugar de la comunidad?",
    t: "Places in the community",
    options: ["Bakery 🥖", "Dog 🐶", "Shoes 👟"], correct: 0,
    explain: "«Bakery» (panadería) es un lugar de la comunidad. Dog es un animal y shoes son zapatos." },

  /* ============ GOODS & SERVICES ============ */
  { topic: "goods", visual: "👟", speak: "Shoes, food and medicine are goods.",
    q: "Shoes, food and medicine are...",
    t: "Los zapatos, la comida y la medicina son...",
    options: ["Goods 🛍️ (bienes)", "Services 🧰 (servicios)", "Places 🗺️ (lugares)"], correct: 0,
    explain: "«Goods» son bienes: cosas que podés comprar y tocar, como shoes, food y medicine." },
  { topic: "goods", visual: "🧰", speak: "The dentist and the fire fighter give us services.",
    q: "The dentist and the fire fighter give us...",
    t: "El dentista y el bombero nos dan...",
    options: ["Goods 🛍️", "Services 🧰", "Toys 🧸"], correct: 1,
    explain: "«Services» son servicios: ayuda que nos dan las personas, como el dentist y el fire fighter." },
  { topic: "goods", visual: "🍞", speak: "Food",
    q: "«Food» es un... / Food is a...",
    t: "La comida, ¿es un bien o un servicio?",
    options: ["Good 🛍️ (bien)", "Service 🧰 (servicio)"], correct: 0,
    explain: "Food (comida) es un good, un bien, porque es algo que se compra y se puede tocar." },
  { topic: "goods", visual: "🏫", speak: "The school is a service.",
    q: "«School» es un... / School is a...",
    t: "La escuela, ¿es un bien o un servicio?",
    options: ["Good 🛍️ (bien)", "Service 🧰 (servicio)"], correct: 1,
    explain: "La school es un service, un servicio, porque nos ayuda enseñándonos. No es algo que se compra en una tienda." },
  { topic: "goods", visual: "💊", speak: "Medicine",
    q: "«Medicine» es un... / Medicine is a...",
    t: "La medicina, ¿es un bien o un servicio?",
    options: ["Good 🛍️ (bien)", "Service 🧰 (servicio)"], correct: 0,
    explain: "Medicine (medicina) es un good, porque la comprás en la drugstore y la podés tocar." },
  { topic: "goods", visual: "🚒", speak: "The fire fighter gives a service.",
    q: "«Fire fighter» da un... / gives a...",
    t: "El bombero, ¿da un bien o un servicio?",
    options: ["Good 🛍️ (bien)", "Service 🧰 (servicio)"], correct: 1,
    explain: "El fire fighter (bombero) da un service: nos ayuda apagando incendios. Las personas que ayudan dan servicios." },

  /* ============ -OP / -OG PHONICS ============ */
  { topic: "phonics", visual: "🐶", speak: "Dog. D-o-g. Dog.",
    q: "Escuchá: ¿cuál palabra es? 🔊",
    t: "Tocá «Escuchar» y elegí la palabra.",
    options: ["dog 🐶", "dot 🔵", "top 🌀"], correct: 0,
    explain: "«Dog» significa perro y termina en -og: d-o-g. Se pronuncia «dog»." },
  { topic: "phonics", visual: "🪵", speak: "Log. L-o-g. Log.",
    q: "Escuchá: ¿cuál palabra es? 🔊",
    t: "Tocá «Escuchar» y elegí la palabra.",
    options: ["leg 🦵", "log 🪵", "lot 📦"], correct: 1,
    explain: "«Log» significa tronco y termina en -og: l-o-g. Rima con dog y fog." },
  { topic: "phonics", visual: "🌫️", speak: "Fog. F-o-g. Fog.",
    q: "¿Qué significa «fog»? 🌫️",
    t: "Es una palabra de la familia -og.",
    options: ["Neblina 🌫️", "Rana 🐸", "Fuego 🔥"], correct: 0,
    explain: "«Fog» significa neblina. Es de la familia -og: dog, log, fog, jog." },
  { topic: "phonics", visual: "🐸", speak: "Frog. Frog jumps on the log.",
    q: "¿Qué significa «frog»? 🐸",
    t: "Es una palabra de la familia -og.",
    options: ["Perro 🐶", "Rana 🐸", "Gato 🐱"], correct: 1,
    explain: "«Frog» significa rana. Frog termina en -og, igual que dog y log." },
  { topic: "phonics", visual: "🌀", speak: "Top. T-o-p. Top.",
    q: "Escuchá: ¿cuál palabra es? 🔊",
    t: "Tocá «Escuchar» y elegí la palabra.",
    options: ["tap 🚰", "top 🌀", "ten 🔟"], correct: 1,
    explain: "«Top» significa trompo o la parte de arriba. Termina en -op: t-o-p." },
  { topic: "phonics", visual: "🧹", speak: "Mop. M-o-p. Mop.",
    q: "¿Qué significa «mop»? 🧹",
    t: "Es una palabra de la familia -op.",
    options: ["Mapa 🗺️", "Palo de piso 🧹", "Mono 🐵"], correct: 1,
    explain: "«Mop» es el palo de piso para limpiar. Es de la familia -op: top, hop, mop, pop." },
  { topic: "phonics", visual: "🐰", speak: "Hop. The rabbit can hop.",
    q: "¿Qué significa «hop»? 🐰",
    t: "The rabbit can hop.",
    options: ["Saltar 🐰", "Dormir 😴", "Comer 🍎"], correct: 0,
    explain: "«Hop» significa saltar en un pie o a brinquitos. El conejo (rabbit) can hop." },
  { topic: "phonics", visual: "🔤", speak: "Dog, log, fog.",
    q: "¿Cuál palabra NO es de la familia -og?",
    t: "Buscá la que termina diferente.",
    options: ["dog 🐶", "cat 🐱", "log 🪵"], correct: 1,
    explain: "«Cat» (gato) termina en -at, no en -og. Dog y log sí son de la familia -og." },
  { topic: "phonics", visual: "🔤", speak: "Top, mop, hop, pop.",
    q: "¿Cuál palabra SÍ es de la familia -op?",
    t: "Buscá la que termina en -op.",
    options: ["sun ☀️", "pop 🎈", "pig 🐷"], correct: 1,
    explain: "«Pop» termina en -op, como top, mop y hop. ¡Pop es el sonido de un globo al explotar!" },

  /* ============ WHERE CAN I...? + DATE ============ */
  { topic: "questions", visual: "🍎", speak: "Where can I get fruits?",
    q: "Where can I get fruits? 🍎",
    t: "¿Dónde puedo conseguir frutas?",
    options: ["At the market 🍎", "At the church ⛪", "At the hospital 🏥"], correct: 0,
    explain: "Las frutas (fruits) se consiguen en el market o con el farmer. «At the market»." },
  { topic: "questions", visual: "🥩", speak: "Who sells meat?",
    q: "Who sells meat? 🥩",
    t: "¿Quién vende carne?",
    options: ["The teacher 🍎", "The butcher 🥩", "The nurse 👩⚕️"], correct: 1,
    explain: "«The butcher» es el carnicero: la persona que vende carne (meat)." },
  { topic: "questions", visual: "💊", speak: "Where can I buy medicine? At the drugstore.",
    q: "Where can I buy medicine?",
    t: "¿Dónde puedo comprar medicina?",
    options: ["At the school 🏫", "At the bakery 🥖", "At the drugstore 💊"], correct: 2,
    explain: "La medicina se compra en la drugstore (farmacia). «At the drugstore»." },
  { topic: "questions", visual: "📅", speak: "Monday, Tuesday, Wednesday, Thursday, Friday.",
    q: "¿Cómo se escribe «viernes» en inglés?",
    t: "Los días de la semana van en mayúscula.",
    options: ["Friday 📅", "Sunday ☀️", "Monday 🌙"], correct: 0,
    explain: "«Friday» es viernes. Sunday es domingo y Monday es lunes. En inglés los días llevan mayúscula." },
  { topic: "questions", visual: "📅", speak: "Today is Friday, September 18th.",
    q: "¿Cuál fecha está bien escrita en inglés?",
    t: "Write the complete date.",
    options: ["friday, september 18th", "Friday, September 18th ✔️", "Viernes 18 de septiembre"], correct: 1,
    explain: "En inglés la fecha lleva mayúsculas: «Friday, September 18th». Primero el día, luego el mes y el número." },
  { topic: "questions", visual: "🗓️", speak: "September",
    q: "¿Qué mes es «September»? 🗓️",
    t: "Escuchá y elegí.",
    options: ["Diciembre 🎄", "Septiembre 🗓️", "Julio ☀️"], correct: 1,
    explain: "«September» es septiembre, el mes nueve del año. ¡El mes de tu examen!" },
  { topic: "questions", visual: "🍞", speak: "Where can I buy bread? At the bakery.",
    q: "Where can I buy bread?",
    t: "¿Dónde puedo comprar pan?",
    options: ["At the bakery 🥖", "At the drugstore 💊", "At the church ⛪"], correct: 0,
    explain: "El pan (bread) se compra en la bakery (panadería). «At the bakery»." }
];

const TOPIC_INFO = {
  helpers:   { label: "Community Helpers", color: "#0ea5e9" },
  places:    { label: "Places", color: "#22c55e" },
  goods:     { label: "Goods & Services", color: "#f59e0b" },
  phonics:   { label: "-op / -og Words", color: "#a855f7" },
  questions: { label: "Where can I...?", color: "#ef4444" }
};
